export const PRODUCTS = [
  {
    imageSrc: '/shovels/welded-shovel.jpg',
    title: 'Лопата штыковая сварная большая 1,5 мм',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 200x270',
    price: '1800',
  },
  {
    imageSrc: '/shovels/welded-shovel.jpg',
    title: 'Лопата штыковая сварная большая 2 мм',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 200x270',
    price: '2000',
  },
  {
    imageSrc: '/shovels/welded-shovel.jpg',
    title: 'Лопата штыковая сварная большая 2,5 мм (по запросу)',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 200x270',
    price: '2500',
  },
  {
    imageSrc: '/shovels/welded-shovel.jpg',
    title: 'Лопата штыковая сварная средняя 2 мм (по запросу)',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 165x230',
    price: '1800',
  },
  {
    imageSrc: '/shovels/welded-shovel.jpg',
    title: 'Лопата штыковая штыковая сварная средняя 1,5 мм',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 165x230',
    price: '1500',
  },
  {
    imageSrc: '/shovels/welded-shovel.jpg',
    title: 'Лопата штыковая сварная средняя 1,2 мм (по запросу)',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 165x230',
    price: '1300',
  },
  {
    imageSrc: '/shovels/welded-shovel.jpg',
    title: 'Лопата штыковая сварная малая 1,5 мм',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 140х200',
    price: '1100',
  },
  {
    imageSrc: '/shovels/welded-shovel.jpg',
    title: 'Лопата штыковая сварная малая 1,2 мм (по запросу)',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 140х200',
    price: '1000',
  },
  {
    imageSrc: '/shovels/stamped-shovel.jpg',
    title: 'Лопата штыковая штампованная 2 мм',
    matirial: `Материал: титановый сплав ВТ1-0`,
    size: 'Размер: 200x270',
    price: '2600',
  },
  {
    imageSrc: '/shovels/stamped-shovel.jpg',
    title: 'Лопата штыковая штампованная 1,5 мм',
    matirial: `Материал: титановый сплав ОТ-4`,
    size: 'Размер: 200x270',
    price: '2400',
  },
  {
    imageSrc: '/shovels/scoop-shovel.jpg',
    title: 'Лопата траншейная  сварная 2 мм',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 200x255',
    price: '2000',
  },
  {
    imageSrc: '/shovels/scoop-shovel.jpg',
    title: 'Лопата траншейная  сварная 2,5 мм (по запросу)',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 200x255',
    price: '2500',
  },
  {
    imageSrc: '/shovels/scoop-shovel-with-board.jpg',
    title: 'Лопата совковая штампованная 1,5 мм без бортов',
    matirial: `Материал: титановый сплав ОТ-4`,
    size: 'Размер: 240x260',
    price: '2400',
  },
  {
    imageSrc: '/shovels/scoop-shovel-with-board.jpg',
    title: 'Лопата совковая штампованная 1,5 мм с бортами',
    matirial: `Материал: титановый сплав ОТ-4`,
    size: 'Размер: 200x270',
    price: '2700',
  },
  // {
  //   imageSrc: '/shovels/DSC05919.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05921.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05924.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05929.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05932.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05933.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05939.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05941.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05942.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05944.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05947.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05954.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05961.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05973.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05974.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05977.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05986.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05996.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05998.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC05999.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC06003.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC06006.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC06009.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC06016.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC06017.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC06021.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC06029.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC06035.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
  // {
  //   imageSrc: '/shovels/DSC06041.jpg',
  //   title: 'Лопата №5',
  //   matirial: `Материал: титановый сплав ВТ20`,
  //   size: 'Размер: 200x270',
  //   price: '1000',
  // },
];
