export const PRODUCTS = [
  {
    imageSrc: '/shovels/welded-shovel.jpg',
    title: 'Лопата штыковая сварная большая 1,5 мм',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 200x270',
    price: '1800',
  },
  {
    imageSrc: '/shovels/welded-shovel.jpg',
    title: 'Лопата штыковая сварная большая 2 мм',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 200x270',
    price: '2000',
  },
  {
    imageSrc: '/shovels/welded-shovel.jpg',
    title: 'Лопата штыковая сварная большая 2,5 мм (по запросу)',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 200x270',
    price: '2500',
  },
  {
    imageSrc: '/shovels/welded-shovel.jpg',
    title: 'Лопата штыковая сварная средняя 2 мм (по запросу)',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 165x230',
    price: '1800',
  },
  {
    imageSrc: '/shovels/welded-shovel.jpg',
    title: 'Лопата штыковая штыковая сварная средняя 1,5 мм',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 165x230',
    price: '1500',
  },
  {
    imageSrc: '/shovels/welded-shovel.jpg',
    title: 'Лопата штыковая сварная средняя 1,2 мм (по запросу)',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 165x230',
    price: '1300',
  },
  {
    imageSrc: '/shovels/welded-shovel.jpg',
    title: 'Лопата штыковая сварная малая 1,5 мм',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 140х200',
    price: '1200',
  },
  {
    imageSrc: '/shovels/welded-shovel.jpg',
    title: 'Лопата штыковая сварная малая 1,2 мм (по запросу)',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 140х200',
    price: '1100',
  },
  {
    imageSrc: '/shovels/stamped-shovel.jpg',
    title: 'Лопата штыковая штампованная 2 мм',
    matirial: `Материал: титановый сплав ВТ1-0`,
    size: 'Размер: 200x270',
    price: '2400',
  },
  {
    imageSrc: '/shovels/stamped-shovel.jpg',
    title: 'Лопата штыковая штампованная 1,5 мм',
    matirial: `Материал: титановый сплав ОТ-4`,
    size: 'Размер: 200x270',
    price: '2200',
  },
  {
    imageSrc: '/shovels/scoop-shovel.jpg',
    title: 'Лопата траншейная  сварная 2 мм',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 200x255',
    price: '2000',
  },
  {
    imageSrc: '/shovels/scoop-shovel.jpg',
    title: 'Лопата траншейная  сварная 2,5 мм (по запросу)',
    matirial: `Материал: титановый сплав ВТ20`,
    size: 'Размер: 200x255',
    price: '2500',
  },
  {
    imageSrc: '/shovels/scoop-shovel-with-board.jpg',
    title: 'Лопата совковая штампованная 1,5 мм без бортов',
    matirial: `Материал: титановый сплав ОТ-4`,
    size: 'Размер: 240x260',
    price: '2400',
  },
  {
    imageSrc: '/shovels/semicircular-chopper.jpg',
    title: 'Тяпка полукруглая 2,5 мм (2,0 мм по запросу)',
    matirial: `Материал: титановый сплав ВТ-20`,
    size: 'Размер: 150х165',
    price: '1200',
  },
  {
    imageSrc: '/shovels/trapezoidal-chopper.png',
    title: 'Тяпка трапецевидная 200, 2,5 мм (2,0 мм по запросу)',
    matirial: `Материал: титановый сплав ВТ-20`,
    size: 'Размер: 150х200',
    price: '1450',
  },
  {
    imageSrc: '/shovels/trapezoidal-chopper.png',
    title: 'Тяпка трапецевидная 170, 2,5 мм (2,0 мм по запросу)',
    matirial: `Материал: титановый сплав ВТ-20`,
    size: 'Размер: 140х170',
    price: '1250',
  },
  {
    imageSrc: '/shovels/axe-shovel.png',
    title: 'Тяпка "Секира" 2,5 мм',
    matirial: `Материал: титановый сплав ВТ-20`,
    size: 'Размер: 150х250',
    price: '1500',
  },
  {
    imageSrc: '/shovels/triangular-chopper.png',
    title: 'Тяпка треугольная 2,5 мм (2,0 мм по запросу)',
    matirial: `Материал: титановый сплав ВТ-20`,
    size: 'Размер: 150х170',
    price: '1300',
  },
];
